services:

  frontend:
    build: ./frontend

    ports:
      - "8501:8501"

    depends_on:
      - backend

  backend:
    build: ./backend

    ports:
      - "8000:8000"

    volumes:
      - ./backend:/app
      - ./backend/logs:/app/logs
